name: React CI/CD

on:
  workflow_dispatch: # Para ejecución manual
  schedule:
    - cron: '45 20 * * 1' # Ejecutar cada lunes a las 20:45 (Hora Boliviana)
    - cron: '45 15 * * 1' # Ejecutar cada lunes a las 15:45 (Hora Boliviana)
  push:
    branches:
      - main
      - release/1.0
      - release/1.1
      - feature/*
      - feature/something
      - feature/something1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      
      - name: Install dependencias
        run: npm install

      - name: Ejecutar pruebas
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      
      - name: Install dependencias
        run: npm install

      - name: Construir la aplicación
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
      
      - name: Desplegar en rama release
        if: startsWith(github.ref, 'refs/heads/release/')
        run: |
          # Comandos para implementar en la rama de release
          # Por ejemplo: npm run deploy-release

      - name: Desplegar en ramas feature
        if: startsWith(github.ref, 'refs/heads/feature/')
        run: |
          # Comandos para implementar en ramas feature
          # Por ejemplo: npm run deploy-feature

